/** React Query hooks for rare variant finder API (P3-30). */

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query"
import type {
  RareVariantFilterRequest,
  RareVariantSearchResponse,
  RareVariantFindingsListResponse,
} from "@/types/rare-variants"

/**
 * Stored rare variant findings for a sample.
 * Returns findings previously generated by search or auto-run.
 * Cached with staleTime: Infinity since findings don't change until re-run.
 */
export function useRareVariantFindings(sampleId: number | null) {
  return useQuery({
    queryKey: ["rare-variant-findings", sampleId],
    queryFn: async (): Promise<RareVariantFindingsListResponse> => {
      const params = new URLSearchParams({ sample_id: String(sampleId!) })
      const res = await fetch(`/api/analysis/rare-variants/findings?${params}`)
      if (!res.ok) {
        const text = await res.text().catch(() => "")
        throw new Error(`Rare variant findings failed: ${res.status}${text ? ` - ${text}` : ""}`)
      }
      return res.json()
    },
    enabled: sampleId != null,
    staleTime: Infinity,
  })
}

/**
 * Search for rare variants with custom filters.
 * Returns matching variants and stores findings.
 * Uses mutation since this is a POST that changes server state.
 */
export function useRareVariantSearch(sampleId: number | null) {
  const queryClient = useQueryClient()
  return useMutation({
    mutationFn: async (filters: RareVariantFilterRequest): Promise<RareVariantSearchResponse> => {
      if (sampleId == null) {
        throw new Error("Cannot search without a sample selected")
      }
      const params = new URLSearchParams({ sample_id: String(sampleId) })
      const res = await fetch(`/api/analysis/rare-variants/search?${params}`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(filters),
      })
      if (!res.ok) {
        const text = await res.text().catch(() => "")
        throw new Error(`Rare variant search failed: ${res.status}${text ? ` - ${text}` : ""}`)
      }
      return res.json()
    },
    onSuccess: () => {
      // Invalidate findings cache after search stores new findings
      queryClient.invalidateQueries({ queryKey: ["rare-variant-findings", sampleId] })
    },
  })
}
